# Generated by Django 3.2.10 on 2022-01-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('class_name', models.CharField(blank=True, max_length=10)),
                ('school', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField(max_length=5)),
                ('physics', models.IntegerField(max_length=5)),
                ('chemistry', models.IntegerField(max_length=5)),
                ('biology', models.IntegerField(max_length=5)),
                ('english', models.IntegerField(max_length=5)),
                ('roll_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentinfo')),
            ],
        ),
    ]
