# Generated by Django 3.2.10 on 2022-01-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademics',
            name='biology',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='chemistry',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='english',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='maths',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='physics',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
